"""add field parent_id in reviews model

Revision ID: 691d8fb51ddb
Revises: 84b16e762063
Create Date: 2025-05-16 20:50:25.274682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691d8fb51ddb'
down_revision: Union[str, None] = '84b16e762063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('parent_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'reviews', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'parent_id')
    # ### end Alembic commands ###
