"""add_dadata_cache

Revision ID: fbabcd192970
Revises: 444f40c7f0ff
Create Date: 2025-06-16 13:14:54.006843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbabcd192970'
down_revision: Union[str, None] = '444f40c7f0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dadata_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_address', sa.String(), nullable=True),
    sa.Column('cleaned_city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dadata_cache_id'), 'dadata_cache', ['id'], unique=False)
    op.create_index(op.f('ix_dadata_cache_original_address'), 'dadata_cache', ['original_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dadata_cache_original_address'), table_name='dadata_cache')
    op.drop_index(op.f('ix_dadata_cache_id'), table_name='dadata_cache')
    op.drop_table('dadata_cache')
    # ### end Alembic commands ###
